[package]
name = "toryn"
version = "0.1.0"
authors = ["Kevin <quebin31@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.26.0-alpha3"
lazy_static = "1.4.0"
glm = "0.2.3"